create TABLE IF NOT EXISTS portal (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,url TEXT,status INTEGER);
insert into portal (name, url, status) values ('Kocaeli Üniversitesi', 'portal.kocaeli.edu.tr', '1');
insert into portal (name, url, status) values ('Enformatik Bölümü', 'enformatik.kocaeli.edu.tr', '1');
insert into portal (name, url, status) values ('Bilgisayar Mühendisliği', 'bilgisayar.kocaeli.edu.tr', '0');
create TABLE IF NOT EXISTS note (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,note TEXT,icon TEXT);
insert into note (title, note, icon) values ('Flask', 'This item Flask', 'flask');
insert into note (title, note, icon) values ('WiFi', 'This item WiFi', 'wifi');
insert into note (title, note, icon) values ('Beer', 'This item Beer', 'beer');
insert into note (title, note, icon) values ('Football', 'This item Football', 'football');
insert into note (title, note, icon) values ('Basketball', 'This item Basketball', 'basketball');
insert into note (title, note, icon) values ('Paper-plane', 'This item Paper-plane', 'paper-plane');
insert into note (title, note, icon) values ('American Football', 'This item American Football', 'american-football');
insert into note (title, note, icon) values ('Boat', 'This item Boat', 'boat');
insert into note (title, note, icon) values ('Bluetooth', 'This item Bluetooth', 'bluetooth');
insert into note (title, note, icon) values ('Build', 'This item Build', 'build');
